name: verona_env_man
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tqdm
  - scipy
  - scikit-learn
  - matplotlib
  - opencv
  - scikit-image
  - tensorboardx
  - fire
  - result
  - onnx
  - pillow
  - requests
  - fire
  - onnxruntime
  - PyYAML
  - seaborn
  - typing_extensions
  - pip
  - pip:
    - onnx2torch  
    - torchattacks
    - tensorboardx
    - -e VERONA